//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project3Datavisualisatie.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Project3Datavisualisatie.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Provincies&quot;;&quot;Bevolking totaal|2005&quot;;&quot;Bevolking totaal|2006&quot;;&quot;Bevolking totaal|2007&quot;;&quot;Bevolking totaal|2008&quot;;&quot;Bevolking totaal|2009&quot;;&quot;Bevolking totaal|2010&quot;;&quot;Bevolking totaal|2011&quot;;&quot;Bevolking totaal|2012&quot;;&quot;Bevolking totaal|2013&quot;;&quot;Bevolking totaal|2014&quot;;&quot;Bevolking totaal|2015&quot;;&quot;Bevolking totaal|2016&quot;
        ///&quot;Groningen (Pr)&quot;;575072;574042;573614;573459;574092;576668;579036;580875;581705;582728;583942;583721
        ///&quot;Friesland&quot;;642977;642230;642209;643189;644811;646305;647282;647214;646862;646317;646257;646040
        ///&quot;Drenthe&quot;;4 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Bevolking {
            get {
                return ResourceManager.GetString("Bevolking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Provincies&quot;;&quot;Misdrijven totaal|2005&quot;;&quot;Misdrijven totaal|2006&quot;;&quot;Misdrijven totaal|2007&quot;;&quot;Misdrijven totaal|2008&quot;;&quot;Misdrijven totaal|2009&quot;;&quot;Misdrijven totaal|2010&quot;;&quot;Misdrijven totaal|2011&quot;;&quot;Misdrijven totaal|2012&quot;;&quot;Misdrijven totaal|2013&quot;;&quot;Misdrijven totaal|2014&quot;;&quot;Misdrijven totaal|2015&quot;;&quot;Misdrijven totaal|2016&quot;
        ///&quot;Groningen (Pr)&quot;;40605;41085;40320;39810;41020;38320;37195;35885;34460;30725;30100;29485
        ///&quot;Friesland&quot;;33705;32410;33725;33300;31375;31795;31945;29905;28760;27620;26595;24545
        ///&quot;Drenthe&quot;;27760;27955;2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Misdrijven {
            get {
                return ResourceManager.GetString("Misdrijven", resourceCulture);
            }
        }
    }
}
