//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project3Datavisualisatie.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Project3Datavisualisatie.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Gemeenten&quot;;&quot;Bevolking totaal|1999&quot;;&quot;Bevolking totaal|2000&quot;;&quot;Bevolking totaal|2001&quot;;&quot;Bevolking totaal|2002&quot;;&quot;Bevolking totaal|2003&quot;;&quot;Bevolking totaal|2004&quot;;&quot;Bevolking totaal|2005&quot;;&quot;Bevolking totaal|2006&quot;;&quot;Bevolking totaal|2007&quot;;&quot;Bevolking totaal|2008&quot;;&quot;Bevolking totaal|2009&quot;;&quot;Bevolking totaal|2010&quot;;&quot;Bevolking totaal|2011&quot;;&quot;Bevolking totaal|2012&quot;;&quot;Bevolking totaal|2013&quot;;&quot;Bevolking totaal|2014&quot;;&quot;Bevolking totaal|2015&quot;;&quot;Bevolking totaal|2016&quot;;&quot;Bevolking totaal|2017&quot;
        ///&quot;Aa en Hunze&quot;;24751;24824;25208;25552;25305 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bevolking {
            get {
                return ResourceManager.GetString("bevolking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Gemeenten&quot;;&quot;Misdrijven totaal|2005&quot;;&quot;Misdrijven totaal|2006&quot;;&quot;Misdrijven totaal|2007&quot;;&quot;Misdrijven totaal|2008&quot;;&quot;Misdrijven totaal|2009&quot;;&quot;Misdrijven totaal|2010&quot;;&quot;Misdrijven totaal|2011&quot;;&quot;Misdrijven totaal|2012&quot;;&quot;Misdrijven totaal|2013&quot;;&quot;Misdrijven totaal|2014&quot;;&quot;Misdrijven totaal|2015&quot;;&quot;Misdrijven totaal|2016&quot;
        ///&quot;Aa en Hunze&quot;;810;890;850;895;800;805;945;940;785;680;645;615
        ///&quot;Aalburg&quot;;500;450;490;445;440;470;490;500;435;425;385;335
        ///&quot;Aalsmeer&quot;;1440;1405;1485;1410;1355;1405;1480;1220;1280;1210;1105;1195
        ///&quot;Aalt [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string misdrijven {
            get {
                return ResourceManager.GetString("misdrijven", resourceCulture);
            }
        }
    }
}
